name: kpconv-pdal-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.1
  - torchvision==0.5.0
  - pytorch==1.4.0
  - pyyaml
  - numpy
  - mayavi
  - scikit-learn
  - pyqt=5
  - cudnn=7.6
  - matplotlib
  - python-pdal
  - tensorboard
